MyApp\UserBundle\Entity\Article:
    type: entity
    table: article
    indexes:
        articleCreatorId:
            columns:
                - articleCreatorId
    id:
        articleid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: articleId
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: integer
            nullable: false
            options:
                unsigned: false
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        flag:
            type: integer
            nullable: false
            options:
                unsigned: false
        date:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        articlecreatorid:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                articleCreatorId:
                    referencedColumnName: userId
            orphanRemoval: false
    lifecycleCallbacks: {  }
