MyApp\UserBundle\Entity\Comment:
    type: entity
    table: comment
    indexes:
        userId:
            columns:
                - userId
        articleId:
            columns:
                - articleId
    id:
        commentid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: commentId
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        flag:
            type: integer
            nullable: false
            options:
                unsigned: false
        date:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        userid:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                userId:
                    referencedColumnName: userId
            orphanRemoval: false
        articleid:
            targetEntity: Article
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                articleId:
                    referencedColumnName: articleId
            orphanRemoval: false
    lifecycleCallbacks: {  }
